Parameters:
  TypeProject:
    Type: String

Resources:
  ArnRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
      Path: '/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: !Sub ${TypeProject}-arn-role-lambda

Outputs:
  ECSCluster:
    Value: !GetAtt ArnRole.Arn
    Export:
      Name: !Sub ${TypeProject}-ArnRole
